/srv/volumes/plex-transcode/*
/srv/volumes/plex-config/Library/Application Support/Plex Media Server/Cache/*
/srv/volumes/plex-config/Library/Application Support/Plex Media Server/Logs/*
/srv/volumes/plex-config/Library/Application Support/Plex Media Server/Crash Reports/*
